"""Report synthesis for DeepLoop research missions.

Generates a research report (LaTeX / PDF) from mission artifacts including
the experiment DAG, bounded memory narrative, and mission state metadata.
"""

from __future__ import annotations

import shutil
import subprocess
from pathlib import Path
from typing import Any

from deeploop.core.bounded_memory import BoundedMemory
from deeploop.core.paths import REPO_ROOT
from deeploop.research.experiment_dag import ExperimentDAG

# Default template path shipped with DeepLoop
_DEFAULT_TEMPLATE_PATH = REPO_ROOT / "configs" / "manifests" / "report-template.tex"
_DEFAULT_OUTPUT_DIR_NAME = "research_report"


def _resolve_value(raw: Any, default: str = "") -> str:
    """Coerce a value to a stripped string, using *default* when empty."""
    if raw is None:
        return default
    text = str(raw).strip()
    return text if text else default


def _format_metrics(metrics: dict[str, float]) -> str:
    """Format a metrics dictionary into a LaTeX-friendly bullet list."""
    if not metrics:
        return "N/A"
    items = " \\\\\n".join(
        f"{k}: {v:.4g}" for k, v in sorted(metrics.items())
    )
    return f"\\begin{{itemize}}\\item {items} \\end{{itemize}}"


def _format_experiment_lineage(dag: ExperimentDAG) -> str:
    """Render the experiment lineage as LaTeX text."""
    if not dag.vertices:
        return "No experiments were recorded."

    # Find root experiments (no parents)
    all_parents: set[str] = set()
    for v in dag.vertices.values():
        all_parents.update(v.parent_ids)
    roots = sorted(vid for vid in dag.vertices if vid not in all_parents)

    lines: list[str] = []
    lines.append("\\begin{enumerate}")
    for root_id in roots:
        lineage = dag.lineage(root_id)
        for vertex in lineage:
            status = vertex.status
            metrics = _format_metrics(vertex.metrics) if vertex.metrics else ""
            label = f"\\texttt{{{vertex.experiment_id}}} (status: {status})"
            if metrics:
                label = f"{label} --- {metrics}"
            lines.append(f"\\item {label}")
    lines.append("\\end{enumerate}")
    return "\n".join(lines)


def _collect_narrative(bounded_memory: BoundedMemory | None) -> str:
    """Extract the research narrative from bounded memory, if available."""
    if bounded_memory is None:
        return ""
    return bounded_memory.memory_log()


def _build_intro(mission_state: dict[str, Any]) -> str:
    """Build the Introduction section from mission state."""
    objective = _resolve_value(mission_state.get("objective"))
    constraints = mission_state.get("constraints") or mission_state.get("autonomy_status", {}).get("constraints")
    if isinstance(constraints, list):
        constraints = "; ".join(str(c) for c in constraints)
    constraints = _resolve_value(constraints)

    parts: list[str] = []
    if objective:
        parts.append(f"\\textbf{{Objective:}} {objective}.\\\\")
    if constraints:
        parts.append(f"\\textbf{{Constraints:}} {constraints}.\\\\")

    # Acceptance criteria
    acceptance = mission_state.get("acceptance_criteria") or mission_state.get("completion_contract")
    if isinstance(acceptance, dict):
        criteria = acceptance.get("criteria") or acceptance.get("requirements")
        if isinstance(criteria, list):
            parts.append("\\textbf{Acceptance Criteria:}")
            parts.append("\\begin{itemize}")
            for c in criteria:
                parts.append(f"  \\item {c}")
            parts.append("\\end{itemize}")

    if not parts:
        parts.append("This report was automatically generated by the DeepLoop autonomous research system.")

    return "\n".join(parts)


def _build_method(mission_state: dict[str, Any], dag: ExperimentDAG | None) -> str:
    """Build the Method section from mission state and experiment DAG."""
    parts: list[str] = []

    model = mission_state.get("model") or mission_state.get("model_config", {})
    if isinstance(model, dict):
        family = _resolve_value(model.get("family") or model.get("name"))
        identifier = _resolve_value(model.get("identifier") or model.get("id"))
        if family:
            parts.append(f"\\textbf{{Model family:}} {family}.\\\\")
        if identifier:
            parts.append(f"\\textbf{{Model identifier:}} {identifier}.\\\\")

    dataset = mission_state.get("dataset")
    if isinstance(dataset, dict):
        name = _resolve_value(dataset.get("name"))
        if name:
            parts.append(f"\\textbf{{Dataset:}} {name}.\\\\")

    if dag is not None:
        parts.append("\\textbf{Experiment lineage:}")
        parts.append(_format_experiment_lineage(dag))

    if not parts:
        parts.append("Method details were not recorded in mission state.")

    return "\n".join(parts)


def _build_results(dag: ExperimentDAG | None, bounded_memory: BoundedMemory | None) -> str:
    """Build the Results section from the DAG and bounded memory."""
    parts: list[str] = []

    if dag is not None:
        completed = [v for v in dag.vertices.values() if v.status == "completed"]
        if completed:
            parts.append("\\textbf{Completed experiments:}")
            parts.append("\\begin{itemize}")
            for v in completed:
                metric_str = _format_metrics(v.metrics) if v.metrics else "no metrics"
                parts.append(f"  \\item \\texttt{{{v.experiment_id}}}: {metric_str}")
            parts.append("\\end{itemize}")

            # SOTA summary
            for v in completed:
                if v.metrics:
                    for metric in v.metrics:
                        sota = dag.get_sota(metric, higher_is_better=True)
                        if sota is not None:
                            parts.append(
                                f"SOTA for \\texttt{{{metric}}}: "
                                f"\\texttt{{{sota.experiment_id}}} "
                                f"({sota.metrics.get(metric, 'N/A'):.4g}).\\\\"
                            )
                            break
                    break

    if bounded_memory is not None:
        narrative = _collect_narrative(bounded_memory)
        if narrative and narrative != "[no dialogue turns]":
            parts.append("\\textbf{Research narrative:}")
            parts.append("\\begin{verbatim}")
            parts.append(narrative)
            parts.append("\\end{verbatim}")

    if not parts:
        parts.append("No results were recorded.")

    return "\n".join(parts)


def _build_conclusion(mission_state: dict[str, Any]) -> str:
    """Build the Conclusion section from mission state."""
    status = _resolve_value(mission_state.get("status", "unknown"))
    summary = _resolve_value(
        mission_state.get("summary")
        or mission_state.get("final_report", {}).get("summary")
        or mission_state.get("completion_summary")
    )
    parts: list[str] = []
    parts.append(f"\\textbf{{Mission status:}} {status}.\\\\")
    if summary:
        parts.append(f"{summary}\\\\")
    else:
        parts.append("This report was automatically generated by the DeepLoop autonomous research system.")
    return "\n".join(parts)


def synthesize_report(
    mission_state: dict,
    experiment_dag: ExperimentDAG | None = None,
    bounded_memory: BoundedMemory | None = None,
    output_dir: Path | None = None,
    *,
    conference: str | None = None,
    experiment_results: dict[str, Any] | None = None,
    statistical_report: dict[str, Any] | None = None,
) -> dict:
    """Generate a research report from mission artifacts.

    Produces LaTeX source and compiles to PDF if ``pdflatex`` is available.

    When *conference* is provided (e.g. ``"iclr2025"``), the full paper
    generation pipeline is used — producing a conference-formatted paper
    with section-by-section LLM generation, figures, and citations.

    Parameters
    ----------
    mission_state:
        The full mission state dictionary containing objective, constraints,
        acceptance criteria, model/dataset metadata, and status.
    experiment_dag:
        Optional :class:`ExperimentDAG` with experiment lineage and metrics.
    bounded_memory:
        Optional :class:`BoundedMemory` with the research narrative.
    output_dir:
        Directory to write the report into.  Defaults to
        ``mission_runtime_root / `` ``research_report`` when the mission
        state contains a ``target_repo`` key, otherwise the current working
        directory.
    conference:
        Optional conference style identifier (``"iclr2025"``, etc.).
        When set, the full paper generation pipeline is used.
    experiment_results:
        Optional dict of experiment results for paper context.
    statistical_report:
        Optional dict of statistical analysis for paper context.

    Returns
    -------
    A dictionary with keys:

    - ``"report_tex_path"`` -- path to the generated ``.tex`` file
    - ``"report_pdf_path"`` -- path to the compiled ``.pdf`` (empty string if
      compilation was skipped or failed)
    - ``"summary"`` -- short human-readable summary of the report
    - ``"output_dir"`` -- the output directory used
    """
    # If a conference is specified, use the full paper generation pipeline
    if conference:
        try:
            from deeploop.paper.generator import generate_paper as gen_paper
            result = gen_paper(
                mission_state,
                conference=conference,
                experiment_results=experiment_results,
                statistical_report=statistical_report,
                output_dir=output_dir,
            )
            return {
                "report_tex_path": result["tex_path"],
                "report_pdf_path": result.get("pdf_path", ""),
                "summary": result["summary"],
                "output_dir": result["output_dir"],
            }
        except Exception:
            # Fall through to the legacy template-based synthesis
            pass
    # --- Resolve output directory ---
    resolved_output_dir: Path
    if output_dir is not None:
        resolved_output_dir = output_dir.expanduser().resolve()
    else:
        target_repo = _resolve_value(mission_state.get("target_repo"))
        if target_repo:
            resolved_output_dir = (
                Path(target_repo).expanduser().resolve()
                / _DEFAULT_OUTPUT_DIR_NAME
            )
        else:
            resolved_output_dir = Path.cwd() / _DEFAULT_OUTPUT_DIR_NAME
    resolved_output_dir.mkdir(parents=True, exist_ok=True)

    # --- Resolve LaTeX template ---
    template_path = _DEFAULT_TEMPLATE_PATH
    if not template_path.exists():
        template_path = resolved_output_dir / "report-template.tex"
        # Write a minimal fallback template
        template_path.write_text(
            "\\documentclass{article}\n"
            "\\title{<<TITLE>>}\n"
            "\\author{DeepLoop Autonomous Research}\n"
            "\\begin{document}\n"
            "\\maketitle\n"
            "\\begin{abstract}<<ABSTRACT>>\\end{abstract}\n"
            "\\section{Introduction}<<INTRODUCTION>>\n"
            "\\section{Method}<<METHOD>>\n"
            "\\section{Results}<<RESULTS>>\n"
            "\\section{Conclusion}<<CONCLUSION>>\n"
            "\\end{document}\n"
        )

    # --- Build sections ---
    title = _resolve_value(mission_state.get("title"), "DeepLoop Research Report")
    objective = _resolve_value(mission_state.get("objective"), "")
    abstract = (
        objective
        if objective
        else f"Autonomous research mission: {title}"
    )
    introduction = _build_intro(mission_state)
    method = _build_method(mission_state, experiment_dag)
    results = _build_results(experiment_dag, bounded_memory)
    conclusion = _build_conclusion(mission_state)

    # --- Read template and substitute ---
    template_text = template_path.read_text(encoding="utf-8")
    substitutions = {
        "<<TITLE>>": title,
        "<<ABSTRACT>>": abstract,
        "<<INTRODUCTION>>": introduction,
        "<<METHOD>>": method,
        "<<RESULTS>>": results,
        "<<CONCLUSION>>": conclusion,
    }
    latex_source = template_text
    for placeholder, value in substitutions.items():
        latex_source = latex_source.replace(placeholder, value)

    # --- Write .tex file ---
    report_tex_path = resolved_output_dir / "research_report.tex"
    report_tex_path.write_text(latex_source, encoding="utf-8")

    # --- Attempt PDF compilation ---
    report_pdf_path: str = ""
    if shutil.which("pdflatex") is not None:
        try:
            result = subprocess.run(
                ["pdflatex", "-interaction=nonstopmode", "-halt-on-error",
                 str(report_tex_path)],
                cwd=resolved_output_dir,
                capture_output=True,
                text=True,
                timeout=120,
                check=False,
            )
            expected_pdf = report_tex_path.with_suffix(".pdf")
            if expected_pdf.exists() and result.returncode == 0:
                report_pdf_path = str(expected_pdf)
            else:
                # Log the error for debugging
                _ = result.stdout[:500] + result.stderr[:500]
        except (subprocess.TimeoutExpired, OSError) as exc:
            # pdflatex timed out or could not be launched
            _ = str(exc)

    summary_parts: list[str] = []
    if report_pdf_path:
        summary_parts.append(f"PDF report generated at {report_pdf_path}")
    summary_parts.append(f"LaTeX source at {report_tex_path}")

    return {
        "report_tex_path": str(report_tex_path),
        "report_pdf_path": report_pdf_path,
        "summary": "; ".join(summary_parts),
        "output_dir": str(resolved_output_dir),
    }
